In [ ]:
import numpy as np

In [ ]:
b= [1,2,3,4]  #(1,4)
c= [[1],
    [2],
    [3],
    [4]]     #(4,1)
a= np.array(b)
d= np.array(c)
z= np.matmul(a,d)
print(b)
print(a)

print(c)
print(type(d))

print("矩阵乘法",z)
print(type(z))

In [ ]:
a2 = np.arange(2,21,2)
print(a2)
print(type(a2))

In [ ]:
for i in range(2,21,2):
    print(i)

In [ ]:
a1 = np.random.random((2,2))
a1

In [ ]:
a2 = np.random.randint(0,10,size=(3,3))
a2

In [ ]:
a1 = np.zeros((2,2))
a1

In [ ]:
a2 = np.ones((2,2))

a2

In [ ]:
print(a2)

In [ ]:
a4 = np.eye(3)
a4

## 1. 默认的数据类型：

In [ ]:
a1 = np.array([1,2,3])
print(a1.dtype) 
# 如果是windows系统，默认是int32
# 如果是mac或者linux系统，则根据系统来

## 2. 指定 dtype ：

In [35]:
import numpy as np
a1 = np.array([1,2,3],dtype=np.int64)
# 或者 a1 = np.array([1,2,3],dtype="i8")
print(a1.dtype)

int64


## 3. 修改 dtype ：

In [36]:
import numpy as np
a1 = np.array([1,2,3])
print(a1.dtype) # window系统下默认是int32

# 以下修改dtype
a2 = a1.astype(np.int64) # astype不会修改数组本身，而是会将修改后的结果返回
print(a2.dtype)

int32
int64


# 数组属性

In [38]:
import numpy as np
a1 = np.array([[1,2,3],[4,5,6]])
print(a1)
print(a1.size) #打印的是6，因为总共有6个元素

[[1 2 3]
 [4 5 6]]
6


## 数组的维度

In [42]:
a1 = np.array([[[1,2,3],[4,5,6]]])
print(a1)
print(a1.ndim)

[[[1 2 3]
  [4 5 6]]]
3


In [ ]:
# [[[1,2,3],
#   [4,5,6]
#   [1,2,3]]    #蓝色
# [[1,2,3],
#   [4,5,6]
#   [1,2,3]]    #红色
# [[1,2,3],
#   [4,5,6]
#   [1,2,3]]]    #绿色

## 数组的形状

In [51]:
a1 = np.array([1,2,3])
print("数组的维度",a1.ndim)
print("数组的形状",a1.shape)

数组的维度 1
数组的形状 (3,)


In [52]:
a1 = np.array([[1,2,3],[4,5,6]])
print("数组的维度",a1.ndim)
print("数组的形状",a1.shape)

数组的维度 2
数组的形状 (2, 3)


In [53]:
a1 = np.array([[[1,2,3],[4,5,6]]])
print("数组的维度",a1.ndim)
print("数组的形状",a1.shape)

数组的维度 3
数组的形状 (1, 2, 3)


In [54]:
a1 = np.array([[[[1,2,3],[4,5,6]]]])
print("数组的维度",a1.ndim)
print("数组的形状",a1.shape)

数组的维度 4
数组的形状 (1, 1, 2, 3)


In [63]:
a1 = np.arange(12) #生成一个有12个数据的一维数组
print(a1) 
a2 = a1.reshape((3,4)) #变成一个2维数组，是3行4列的
print(a2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [43]:
import cv2 as cv

In [55]:
img= cv.imread("image.jpg")

img1= img.T

In [65]:
print("图片的维度",img1.ndim)
print("图片的维度",img1.shape)  #

图片的维度 3
图片的维度 (3, 247, 175)


# Numpy数组操作

## 数组与数的计算：

In [68]:
import numpy as np
a1 = np.random.random((3,4))
print(a1)
# 如果想要在a1数组上所有元素都乘以10，那么可以通过以下来实现
a2 = a1*10
print(a2)
# # 也可以使用round让所有的元素只保留2位小数
# a3 = a2.round(2)

[[0.86819046 0.55984566 0.4191588  0.56347809]
 [0.91381101 0.03407021 0.03925207 0.61705755]
 [0.06150206 0.71493505 0.72392219 0.55646284]]
[[8.68190464 5.59845659 4.19158799 5.63478086]
 [9.13811005 0.3407021  0.39252067 6.1705755 ]
 [0.61502058 7.14935046 7.2392219  5.56462843]]


In [71]:
# a3=[1,2,3]
# a3 = a3*5
# a3

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

## 数组与数组的计算：

In [74]:
a1 = np.arange(0,24).reshape((3,8))
a2 = np.random.randint(1,10,size=(3,8))
a1+a2

array([[ 8,  7,  3, 12, 13,  6,  7, 15],
       [ 9, 17, 19, 14, 14, 16, 22, 24],
       [20, 24, 21, 20, 25, 24, 23, 26]])

### 数组广播机制：

In [84]:
a1 = np.random.randint(10,20,size=(3,8)) #3行8列
a2 = np.random.randint(1,10,size=(1,8)) #3行1列
a3 = a1 - a2 #行数相同，且a2只有1列，能互相运算
print(a1,"\n")
print(a2,"\n")
print(a3,"\n")

[[10 15 11 15 18 14 13 16]
 [19 19 11 10 14 16 14 15]
 [14 14 14 14 11 19 10 12]] 

[[4 3 8 6 4 1 7 9]] 

[[ 6 12  3  9 14 13  6  7]
 [15 16  3  4 10 15  7  6]
 [10 11  6  8  7 18  3  3]] 



In [77]:
a1 = np.random.randint(10,20,size=(3,8)) #3行8列
a2 = np.random.randint(1,10,size=(1,8))
a3 = a1 - a2
print(a3)

[[ 5  1 11 12 11 16  9  5]
 [ 5  7 14 15  6 16  9  5]
 [ 6  1 14 10  7  8 10  8]]


In [79]:
a1 = np.random.randint(10,20,size= (3,8,2)) #3行8列
a2 = np.random.randint(1,10,size=  (8,1))
a3 = a1 - a2
print(a3)

[[[11 11]
  [12 12]
  [11  4]
  [10 10]
  [14 13]
  [ 8 11]
  [ 9 14]
  [ 3  5]]

 [[ 3  4]
  [ 9 10]
  [ 7  8]
  [10  9]
  [14 18]
  [ 7 11]
  [14 13]
  [ 8  1]]

 [[ 5  3]
  [13 14]
  [ 6  6]
  [ 5 13]
  [ 9 16]
  [ 6  4]
  [11 16]
  [ 5  3]]]


## 数组形状的操作：

In [88]:
a1 = np.random.randint(0,10,size=(3,4))
a2 = a1.reshape((2,6)) #将修改后的结果返回，不会影响原数组本身
a1
a2

array([[5, 4, 9, 1, 6, 4],
       [1, 2, 9, 9, 2, 6]])

In [86]:
a1 = np.random.randint(0,10,size=(3,4))
a1.resize((2,6)) #a1本身发生了改变
a1

array([[7, 9, 9, 8, 8, 4],
       [0, 6, 8, 9, 7, 2]])