In [1]:
import numpy as np

## 1. 如何查看numpy的版本号

In [2]:
print(np.__version__)

1.19.5


## 2. 如何创建一个所有值都是False的布尔类型的数组

In [3]:
np.full((3,3),False,dtype=np.bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

## 3. 将一个有10个数的数组的形状进行转换

In [4]:
## 1. 使用shape实现
arr = np.arange(10)
# arr.reshape(5,2) #使用reshape的方式
arr[:np.newaxis] #np.newaxis所在的位置会变成1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 4. 将数组中所有偶数都替换成0（改变原来数组和不改变原来数组两种方式实现）

In [5]:
arr = np.random.randint(0,10,size=(3,3))
# 1. 不改变原来数组
arr1 = np.where(arr%2==0,0,arr)
print(arr1)
# 2. 改变原来数组
arr[arr%2==0] = 0
print("="*30)
print(arr)

[[7 1 0]
 [3 1 0]
 [0 0 9]]
[[7 1 0]
 [3 1 0]
 [0 0 9]]


## 5. 求以下数组大于等于5并且小于等于10的数组

In [6]:
arr = np.linspace(0,1,12)[1:-1]
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

## 6. 求以下数组大于等于5并且小于等于10的数组

In [7]:
a= np.arange(15)
# 方法1
index = np.where((a >= 5) & (a <= 10))
a[index]

# 方法2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
#> (array([6, 9, 10]),)

# 方法3：
a[(a >= 5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

## 7. 将一个二维数组的行和列分别进行逆向

In [8]:
a = np.arange(15).reshape(3,5)
# 反转行
a1 = a[::-1] #里面传一个数进去（没有出现逗号），代表的是只对行进行操作
print(a1)
# 反转列
a2 = a[:,::-1] #里面传两个数进去，第一个是所有的行，第二个就是针对所有的列，但是取值的方向是从后面到前面。
print("="*30)
print(a2)

[[10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]]


## 8. 如何将科学计数法转换为浮点类型打印

In [9]:
# set_printoptions用来设置打印的时候的一些配置和选项
# 将suppress设置为True，就不会显示成科学计数法了，并且通过precision来控制小数点后要保留几位
np.set_printoptions(suppress=True,precision=6)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)

[[0.00059  0.000729 0.000765]
 [0.00055  0.000399 0.000684]
 [0.000647 0.000455 0.000496]]


## 9. 获取一个数组中唯一的元素

In [10]:
arr = np.random.randint(0,20,(10,10))
np.unique(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## 10. 获取一个数组中唯一的元素个数的排行

In [11]:
arr = np.random.randint(0,20,(10,10))
np.unique(arr,return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),
 array([ 4,  5,  4,  5,  3,  3,  4,  8,  8,  4, 10,  5,  8,  3,  2,  4,  9,
         3,  4,  4], dtype=int64))

## 11. 如何获取一个数组中每行的最大值

In [12]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
print("="*30)
print(np.amax(a,axis=1))

# 或者是
print(np.apply_along_axis(np.max,arr=a,axis=1))

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
[9 8 6 3 9]
[9 8 6 3 9]


## 12. 如何按照行求最小值与最大值相除的结果

In [13]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
np.apply_along_axis(lambda x: np.min(x)/np.max(x),arr=a,axis=1)

array([0.444444, 0.125   , 0.5     , 1.      , 0.111111])

## 13. 判断两个数组是否相等

In [14]:
a = np.array([0,1,2])
b = np.arange(3)
(a == b).all()

True

## 14. 设置一个数组不能修改值

In [15]:
a = np.zeros((2,2))
a.flags.writable = False
a[0] = 1

AttributeError: 'numpy.flagsobj' object has no attribute 'writable'

## 15. 找到数组中离某个元素的最近的值

In [ ]:
np.random.seed(100)
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z[np.abs(Z - z).argmin()]
print(m)