In [13]:
import numpy as np
print(np.__version__)

1.19.5


In [8]:
a1 = np.random.random((2, 2)) # 生成2行2列的随机数的数组
a2 = np.random.randint(0,10,size=(3,3)) # 元素是从0-10之间随机的3行3列的数组
print(a1)
print(a2)

[[0.61949866 0.3379442 ]
 [0.44419529 0.83438763]]
[[2 4 5]
 [5 6 3]
 [6 7 8]]


In [12]:
a4 = np.array([[1,2,3],[4,5]])
print(a4.shape) # 输出(2,)，意思是a4是一个一维数组，总共有2列
print(a4) # 输出[list([1, 2, 3]) list([4, 5])]，其中最外面层是数组，里面是Python列表

(2,)
[list([1, 2, 3]) list([4, 5])]


d:\python3.6.6\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.
