### vstack

In [1]:
import numpy as np

In [10]:
a1 = np.random.randint(0,10,size=(3,5))
a2 = np.random.randint(0,10,size=(1,5))

In [11]:
a1

array([[8, 6, 4, 9, 7],
       [2, 2, 0, 3, 5],
       [2, 9, 1, 7, 4]])

In [12]:
a2

array([[6, 6, 5, 5, 3]])

In [13]:
a3 = np.vstack([a1,a2])
a3

array([[8, 6, 4, 9, 7],
       [2, 2, 0, 3, 5],
       [2, 9, 1, 7, 4],
       [6, 6, 5, 5, 3]])

### hstack

In [25]:
a1 = np.random.randint(0,10,size=(3,2))
a2 = np.random.randint(0,10,size=(3,1))

In [26]:
a1

array([[8, 9],
       [2, 7],
       [6, 1]])

In [27]:
a2

array([[9],
       [6],
       [2]])

In [28]:
a3 = np.hstack([a1,a2])

### concatenate([],axis)

In [32]:
a = np.array([[1, 2],
              [3, 4]])  #(2,2)

b = np.array([[5, 6]]).T         #(1,2)
print(b)
np.concatenate((a, b), axis=1)

[[5]
 [6]]


array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
(2,3)
(2,3).T
(2,3) (3,2)  (2,2)
