In [2]:
import numpy as np

### 获取某行的数据：

In [20]:
# a1 = np.arange(0,29)
# print(a1[3])
# print(a1)#获取下标为1的元素
a1 = np.arange(0,24).reshape((4,6))
print(a1[1][1])
# print(a1[1]) #获取下标为1的行的数据 

7


### 连续获取某几行的数据：

In [19]:
a1 = np.arange(0,24).reshape((4,6))
print(a1,"\n")
print(a1[0:2]) #获取0行到1行的数据

# print(a1[[0,2,3]])

# print(a1[[-1,-4]])   #print(a1[[0,3]])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] 



###  获取某行某列的数据：

In [25]:
a1 = np.arange(0,24).reshape((4,6))
# print(a1[1,1]) #获取1行1列的数据
# print(a1[0:2,2:4]) #获取0-1行的0-1列的数据
print(a1[[1,2],[2,3]]) #获取(1,2)和(2,3)的两个数据，这也叫花式索引

[ 8 15]


In [26]:
a1 = np.arange(0,24).reshape((4,6))
print(a1[:,2:4]) #获取0-1行的0-1列的数据

[[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]]


### 案例

In [86]:
# import cv2 as cv

# img= cv.imread("image.jpg")
# img.shape

# b = img[:,:,0]
# # g = img[:,:,1]
# # r = img[:,:,2]

# b = np.zeros((549, 877)).astype(np.uint8)
# g = np.zeros((549, 877)).astype(np.uint8)
# img_test= cv.merge((b,g,r))
# # type(g[0][0])
# img_test.shape

# cv.imshow("img_test",img_test)
# cv.waitKey(0)

### 布尔索引：

In [93]:
a1 = np.arange(0,24).reshape((4,6))
# print(a1<10)   #a<10
a1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [95]:
a1 = np.arange(0,24).reshape((4,6))
a2 = a1 < 10
print(a1[a2]) #这样就会在a1中把a2中为True的元素对应的位置的值提取出来

[0 1 2 3 4 5 6 7 8 9]


In [94]:
# a= np.random.randint(60,100,size=(10,3))
# a

In [101]:
a= np.random.randint(60,100,size=(4,4))
b= np.eye(4,dtype=bool)
print(a)
print(a[b])

[[65 89 65 88]
 [82 61 63 75]
 [71 92 99 91]
 [69 93 73 87]]
[65 61 99 87]


In [110]:
a= np.arange(10)

a[a%2!=0]=-1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [112]:
a1 = np.arange(0,24).reshape((4,6))
print(a1)
a2 = a1[(a1 < 5) | (a1 > 10)]
print(a2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[ 0  1  2  3  4 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [113]:
a1 = np.arange(0,24).reshape((4,6))
a1[3] = 0 #将第三行的所有值都替换成0
print(a1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [ 0  0  0  0  0  0]]
