In [1]:
import numpy as np

### reshape

In [3]:
a1 = np.random.randint(0,10,size=(3,4))
a1

array([[3, 0, 1, 7],
       [4, 0, 4, 0],
       [1, 7, 3, 6]])

In [5]:
a2 = a1.reshape((2,6))
a2

array([[3, 0, 1, 7, 4, 0],
       [4, 0, 1, 7, 3, 6]])

In [6]:
a1

array([[3, 0, 1, 7],
       [4, 0, 4, 0],
       [1, 7, 3, 6]])

### resize

In [7]:
a1.resize((2,6))

In [8]:
a1

array([[3, 0, 1, 7, 4, 0],
       [4, 0, 1, 7, 3, 6]])

### flatten和ravel方法：

In [10]:
x = np.array([[1, 2], [3, 4]])
x.flatten()[1] = 100 #此时的x[0]的位置元素还是1
x

array([[1, 2],
       [3, 4]])

In [11]:
x.ravel()[1] = 100 #此时x[0]的位置元素是100
x

array([[  1, 100],
       [  3,   4]])

### 不拷贝：

In [17]:
a = np.arange(12)
print(a)
b = a #这种情况不会进行拷贝
print(b is a) #返回True，说明b和a是相同的
b[1]=0
a

[ 0  1  2  3  4  5  6  7  8  9 10 11]
True


array([ 0,  0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### View或者浅拷贝：

In [21]:
a = np.arange(12)
print(a)
c = a.view()
print(c is a) #返回False，说明c和a是两个不同的变量
c[1]=0
c
a
# c[0] = 100
# print(a[0]) #打印100，说明对c上的改变，会影响a上面的值，说明他们指向的内存空间还是一样的，这种
# 叫做浅拷贝，或者说

[ 0  1  2  3  4  5  6  7  8  9 10 11]
False


array([ 0,  0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 深拷贝：

In [26]:
a = np.arange(12)
print(a)
d = a.copy()
print(d is a) #返回False，说明d和a是两个不同的变量
d[1]=0
d
a 
# d[0] = 100
# print(a[0])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
False


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- 不拷贝  a = b
- 浅拷贝  b = np.view(a)
- 深拷贝  d = np.copy(a)