In [1]:
import numpy as np

In [2]:
#  ndarray.ndim：数组的维数
a1 = np.array([1,2,3])
print(a1.ndim)
a2 = np.array([[1,2,3],[4,5,6]])
print(a2.ndim)
a3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(a3.ndim)

1
2
3


In [3]:
#  ndarray.shape ：数组的维度的元组
print(a1.shape)
print(a2.shape)
print(a3.shape)  # 输出(2,2,3)，意思是三维数组，总共有2个元素，每个元素是2行3列的

(3,)
(2, 3)
(2, 2, 3)


In [4]:
# 通过 ndarray.reshape 来重新修改数组的维数
a4 = a3.reshape((2,6))
print(a4)
print(a4.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [5]:
# a5 = a3.reshape((1,12))
# a5 = a3.reshape((12,))
a5 = a3.flatten()   # 将一个多维数组a3展平成一维数组a5
print(a5)
print(a5.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [6]:
count = a3.size  # 用于计算数组a3中元素的个数，并将结果存储到变量count中
print(count)

12


In [8]:
# 用于获取数组a3中每个元素的字节大小（itemsize），以及整个数组占用的内存空间大小。
print(a3)
itemsize = a3.itemsize
print(itemsize)     # 打印4，因为每个字节是8位，32位/8=4个字节
print(a3.dtype)
print(itemsize*a3.size)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
4
int32
48


# 总结：
1. 数组一般达到3维就已经很复杂了，不太方便计算了，所以我们一般都会把3维以上的数组转换成2维数组来计算。
2. 通过ndarray.ndim可以看到数组的维度。
3. 通过ndarray.shape可以看到数组的形状（几行几列），shape是一个元组，里面有几个元素代表是几维数组。
4. 通过ndarray.reshape可以修改数组的形状。条件只有一个，就是修改后的形状的元素个数必须和原来的个数一致。比如原来是(2,6)，那么修改完成后可以变成(3,4)，但是不能变成(1,4)。reshape不会修改原来数组的形状，他只会将修改后的结果返回。
5. 通过ndarray.size可以看到数组总共有多少个元素。
6. 通过ndarray.itemsize可以看到数组中每个元素所占内存的大小，单位是字节。（1个字节=8位）。