In [16]:
import numpy as np

In [17]:
# 1. 一维数组的索引和切片
a1 = np.arange(10)
# 1.1 进行索引操作
print(a1[4])
# 1.2 进行切片操作
print(a1[4:6])
# 1.3 使用步长
# print(a1[::2])
# 1.4 使用负数来作为索引
print(a1[-1])

4
[4 5]
9


In [18]:
# 2. 多维数组
# 也是通过中括号来索引和切片，在中括号中，使用逗号进行分割，逗号前面的是行，逗号后面的
# 是列，如果多维数组中只有一个值，那么这个值就是行
a2 = np.random.randint(0,10,size=(4,6))
print(a2)

[[3 3 8 4 2 1]
 [9 5 7 5 0 3]
 [8 5 4 7 9 3]
 [0 2 1 8 2 1]]


In [19]:
print(a2[0][0])

3


In [20]:
print(a2[0])
print(a2[1:3])
print(a2[[0,2,3]])

[3 3 8 4 2 1]
[[9 5 7 5 0 3]
 [8 5 4 7 9 3]]
[[3 3 8 4 2 1]
 [8 5 4 7 9 3]
 [0 2 1 8 2 1]]


In [21]:
# a2[2,1]
print(a2[[1,2],[4,5]])
print(a2[1:3,4:6])
# a2[1:3,4:6]
# a2[:,[1,3]]

[0 3]
[[0 3]
 [9 3]]


# 索引和切片总结：
1. 如果数组是一维的，那么索引和切片就是跟python的列表是一样的。
2. 如果是多维的（这里以二维为例），那么在中括号中，给两个值，两个值是通过逗号分隔的，逗号前面的是行，逗号后面的是列。如果中括号中只有一个值，那么就是代表的是行。
3. 如果是多维数组（这里以二维为例），那么行的部分和列的部分，都是遵循一维数组的方式，可以使用整形，切片，还可以使用中括号的形式，来代表不连续的。比如a[[1,2],[3,4]]，那么返回的就是(1,3),(2,4)的两个值。

In [22]:
a2 = np.arange(24).reshape((4,6))
print(a2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [23]:
a2 < 10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [24]:
a2[a2 < 10]   #  #这样就会在a2中  把a2中为True的元素  对应的位置的值提取出来

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a2[(a2 < 5) | (a2 > 10)]

array([ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23])

# 布尔索引：
布尔索引是通过相同数组上的True还是False来进行提取的。提取的条件可以有多个，那么如果有多个，可以使用&来代表且，用|来代表或，如果有多个条件，那么每个条件要使用圆括号括起来。

In [26]:
a3 = np.random.randint(0,10,size=(3,5))
a3

array([[8, 9, 7, 4, 7],
       [9, 1, 6, 3, 9],
       [0, 7, 7, 8, 6]])

In [27]:
a3[1] = np.array([1,2,3,4,5])  # 将第2行的所有值都替换成[1,2,3,4,5]
a3

array([[8, 9, 7, 4, 7],
       [1, 2, 3, 4, 5],
       [0, 7, 7, 8, 6]])

In [28]:
a3[a3 < 3] = 1
a3

array([[8, 9, 7, 4, 7],
       [1, 1, 3, 4, 5],
       [1, 7, 7, 8, 6]])

In [29]:
result = np.where(a3<5,0,1)
result

array([[1, 1, 1, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 1, 1, 1]])

# 值的替换总结：
1. 可以使用索引或者切片来替换。
2. 使用条件索引来替换。
3. 使用where函数来实现。