In [1]:
import numpy as np

In [2]:
a1 = np.random.randint(0,5,size=(3,5))
a1

array([[4, 3, 4, 0, 1],
       [2, 4, 0, 1, 1],
       [1, 1, 3, 4, 2]])

In [3]:
a1*2

array([[8, 6, 8, 0, 2],
       [4, 8, 0, 2, 2],
       [2, 2, 6, 8, 4]])

In [4]:
a2 = np.random.randint(0,5,size=(3,5))
a2

array([[1, 0, 1, 4, 2],
       [4, 4, 0, 2, 4],
       [1, 2, 4, 1, 1]])

In [5]:
a1+a2

array([[5, 3, 5, 4, 3],
       [6, 8, 0, 3, 5],
       [2, 3, 7, 5, 3]])

In [6]:
a3 = np.random.randint(0,5,size=(3,4))
a3

array([[3, 1, 4, 2],
       [3, 0, 1, 4],
       [2, 0, 2, 3]])

In [7]:
a1+a3

ValueError: operands could not be broadcast together with shapes (3,5) (3,4) 

In [9]:
a4 = np.random.randint(0,5,size=(3,1))
print(a1)
print('='*30)
print(a4)

[[4 3 4 0 1]
 [2 4 0 1 1]
 [1 1 3 4 2]]
[[2]
 [0]
 [1]]


In [10]:
a1+a4

array([[6, 5, 6, 2, 3],
       [2, 4, 0, 1, 1],
       [2, 2, 4, 5, 3]])

In [12]:
a5 = np.random.randint(0,5,size=(1,5))
print(a1)
print("="*30)
print(a5)

[[4 3 4 0 1]
 [2 4 0 1 1]
 [1 1 3 4 2]]
[[3 1 3 3 0]]


In [13]:
a1+a5

array([[7, 4, 7, 3, 1],
       [5, 5, 3, 4, 1],
       [4, 2, 6, 7, 2]])

In [14]:
a6 = np.random.randint(0,5,size=(3,8,2))
a7 = np.random.randint(0,5,size=(8,2))
print(a6)
print("="*30)
print(a7)
print("="*30)
print(a6+a7)

[[[1 0]
  [2 1]
  [4 1]
  [1 2]
  [2 4]
  [0 3]
  [4 2]
  [0 0]]

 [[2 1]
  [3 3]
  [4 0]
  [4 1]
  [1 4]
  [4 0]
  [0 4]
  [4 3]]

 [[1 1]
  [2 0]
  [2 4]
  [0 4]
  [0 4]
  [2 4]
  [4 0]
  [2 0]]]
[[1 2]
 [4 0]
 [1 3]
 [4 3]
 [3 2]
 [4 2]
 [3 4]
 [2 3]]
[[[2 2]
  [6 1]
  [5 4]
  [5 5]
  [5 6]
  [4 5]
  [7 6]
  [2 3]]

 [[3 3]
  [7 3]
  [5 3]
  [8 4]
  [4 6]
  [8 2]
  [3 8]
  [6 6]]

 [[2 3]
  [6 0]
  [3 7]
  [4 7]
  [3 6]
  [6 6]
  [7 4]
  [4 3]]]


# 总结：
1. 数组和数字直接进行运算是没有问题的。
2. 两个shape相同的数组是可以进行运算的。
3. 如果两个shape不同的数组，想要进行运算，那么需要看他们是否满足广播原则。
4. 如果两个数组的后缘维度（trailing dimension，即从末尾开始算起的维度）的轴长度相符或其中一方的长度为1，则认为他们是广播兼容的。广播会在缺失和（或）长度为1的维度上进行。