In [11]:
import numpy as np

In [12]:
a= np.arange(12)
b = a #这种情况不会进行拷贝
print(b is a) #返回True，说明b和a是相同的

True


In [13]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### View或者浅拷贝：有些情况，会进行变量的拷贝，但是他们所指向的内存空间都是一样的，那么这种情况叫做浅拷贝，或者叫做 View(视图)

In [20]:
c = a.view()
# print(c is a)
c[0] = 100
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [21]:
print(c)

[100   1   2   3   4   5   6   7   8   9  10  11]


### 深拷贝：将之前数据完完整整的拷贝一份放到另外一块内存空间中，这样就是两个完全不同的值了

In [15]:
d = a.copy()
# print(d is a)
d[1] = 200
d

array([100, 200,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [16]:
a1 = np.random.rand(2,4)
a1

array([[0.40947065, 0.09786649, 0.9945701 , 0.11647133],
       [0.59078357, 0.21776779, 0.83236759, 0.30648493]])

### 像前面讲到的 flatten 和 ravel 就是这种情况， ravel 返回的就是View，而 flatten 返回的就是深拷贝。

In [17]:
a2 = a1.ravel()
a2[0] = 0
a1 #修改了a1的值，说明ravel返回的是一个浅拷贝

array([[0.        , 0.09786649, 0.9945701 , 0.11647133],
       [0.59078357, 0.21776779, 0.83236759, 0.30648493]])

In [18]:
a3 = a1.flatten()
a3[1] = 100
a3

array([  0.        , 100.        ,   0.9945701 ,   0.11647133,
         0.59078357,   0.21776779,   0.83236759,   0.30648493])

# 总结：
在数组操作中分成三种拷贝：
1. 不拷贝：直接赋值，那么栈区没有拷贝，只是用同一个栈区定义了不同的名称。
2. 浅拷贝：只拷贝栈区，栈区指定的堆区并没有拷贝。
3. 深拷贝：栈区和堆区都拷贝了。