In [1]:
import numpy as np

In [2]:
scores = np.random.randint(0,100,size=(20,2))
scores

array([[96,  9],
       [67,  8],
       [51, 94],
       [70, 23],
       [97, 30],
       [47, 66],
       [52, 60],
       [54, 65],
       [33, 16],
       [77, 72],
       [77, 20],
       [76, 38],
       [22, 73],
       [14, 64],
       [87,  7],
       [62, 22],
       [60, 20],
       [ 4, 46],
       [78,  8],
       [87, 91]])

In [3]:
np.savetxt("score.csv",scores,delimiter=",",header="英语,数学",comments="",fmt="%d")
# help(np.savetxt)

In [4]:
b = np.loadtxt("score.csv",dtype=np.int,delimiter=",",skiprows=1)
b

array([[96,  9],
       [67,  8],
       [51, 94],
       [70, 23],
       [97, 30],
       [47, 66],
       [52, 60],
       [54, 65],
       [33, 16],
       [77, 72],
       [77, 20],
       [76, 38],
       [22, 73],
       [14, 64],
       [87,  7],
       [62, 22],
       [60, 20],
       [ 4, 46],
       [78,  8],
       [87, 91]])

In [5]:
c = np.random.randint(0,10,size=(2,3))
np.save("c",c)

In [6]:
c1 = np.load("c.npy")
c1

array([[8, 7, 7],
       [5, 7, 4]])

In [7]:
d = np.random.randint(0,10,size=(2,3,4))
# np.savetxt("d.csv",d)
np.save("d",d)

# 总结：
1. np.savetxt和np.loadtxt一般用来操作csv文件，他可以设置header，但是不能存储3维以上的数组。
2. np.save和np.load一般用来存储非文本类型的文件，他不可以设置header，但是可以存储3维以上的数组。
3. 如果想专门的操作CSV文件，其实还有另外一个模块叫做csv，这个模块是python内置的，不需要安装。