In [1]:
import numpy as np

In [2]:
a = np.random.uniform(-10,10,size=(3,5))
a

array([[-6.71149229, -2.17809525,  8.57545287, -5.31680944, -5.84956773],
       [-8.57309185, -5.76927816, -9.8563885 ,  2.79138433, -1.8064904 ],
       [-6.96541888, -2.77797572, -6.22511018, -7.55583726,  0.24365377]])

##### 链接：http://blog.csdn.net/BaoITcore/article/details/125273828   详述numpy中的np.random.rand()、np.random.randn()、np.random.randint()、np.random.uniform()函数的用法与区别 

In [3]:
# 1. np.abs
np.abs(a)

array([[6.71149229, 2.17809525, 8.57545287, 5.31680944, 5.84956773],
       [8.57309185, 5.76927816, 9.8563885 , 2.79138433, 1.8064904 ],
       [6.96541888, 2.77797572, 6.22511018, 7.55583726, 0.24365377]])

In [4]:
# 2. np.sqrt
np.sqrt(a)

D:\ProgramApp\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([[       nan,        nan, 2.92838742,        nan,        nan],
       [       nan,        nan,        nan, 1.67074364,        nan],
       [       nan,        nan,        nan,        nan, 0.49361298]])

In [5]:
# 3. np.square
np.square(a)

array([[4.50441288e+01, 4.74409890e+00, 7.35383919e+01, 2.82684626e+01,
        3.42174426e+01],
       [7.34979038e+01, 3.32845704e+01, 9.71483943e+01, 7.79182645e+00,
        3.26340755e+00],
       [4.85170601e+01, 7.71714912e+00, 3.87519968e+01, 5.70906766e+01,
        5.93671608e-02]])

In [6]:
# 4. np.exp
np.exp(a)

array([[1.21684688e-03, 1.13257052e-01, 5.29995109e+03, 4.90838930e-03,
        2.88114432e-03],
       [1.89126993e-04, 3.12201031e-03, 5.24112914e-05, 1.63035736e+01,
        1.64229507e-01],
       [9.43967446e-04, 6.21642176e-02, 1.97910575e-03, 5.23048034e-04,
        1.27590250e+00]])

In [7]:
# 5. np.log
np.log(a)

D:\ProgramApp\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


array([[        nan,         nan,  2.1489038 ,         nan,         nan],
       [        nan,         nan,         nan,  1.02653765,         nan],
       [        nan,         nan,         nan,         nan, -1.41200703]])

In [8]:
# 6. np.sign
np.sign(a)

array([[-1., -1.,  1., -1., -1.],
       [-1., -1., -1.,  1., -1.],
       [-1., -1., -1., -1.,  1.]])

In [9]:
# 7. np.ceil
np.ceil(a)

array([[-6., -2.,  9., -5., -5.],
       [-8., -5., -9.,  3., -1.],
       [-6., -2., -6., -7.,  1.]])

In [10]:
# 8. np.floor
np.floor(a)

array([[ -7.,  -3.,   8.,  -6.,  -6.],
       [ -9.,  -6., -10.,   2.,  -2.],
       [ -7.,  -3.,  -7.,  -8.,   0.]])

In [11]:
# 8. np.rint或者np.round
np.rint(a)

array([[ -7.,  -2.,   9.,  -5.,  -6.],
       [ -9.,  -6., -10.,   3.,  -2.],
       [ -7.,  -3.,  -6.,  -8.,   0.]])

In [13]:
# 9. np.modf
np.modf(a)[1]

array([[-6., -2.,  8., -5., -5.],
       [-8., -5., -9.,  2., -1.],
       [-6., -2., -6., -7.,  0.]])

In [14]:
# 10. np.sin
np.sin(a)

array([[-0.41533131, -0.82119239,  0.7508348 ,  0.82283158,  0.42015632],
       [-0.75239214,  0.49158346,  0.41833419,  0.3430935 , -0.9723525 ],
       [-0.63052822, -0.35565699,  0.05804249, -0.95588322,  0.24125008]])

In [21]:
a+1

array([[-5.71149229, -1.17809525,  9.57545287, -4.31680944, -4.84956773],
       [-7.57309185, -4.76927816, -8.8563885 ,  3.79138433, -0.8064904 ],
       [-5.96541888, -1.77797572, -5.22511018, -6.55583726,  1.24365377]])

In [24]:
np.add(a,np.random.randint(0,5,size=(3,1)))

array([[-4.71149229, -0.17809525, 10.57545287, -3.31680944, -3.84956773],
       [-6.57309185, -3.76927816, -7.8563885 ,  4.79138433,  0.1935096 ],
       [-5.96541888, -1.77797572, -5.22511018, -6.55583726,  1.24365377]])

In [27]:
# a[a > 0]
a[np.greater(a,0)]

array([8.57545287, 2.79138433, 0.24365377])

In [29]:
# a[(a > 0) & (a < 5)]
a[np.logical_and(a>0,a<5)]

array([2.79138433, 0.24365377])

In [33]:
# a[(a > 5) | (a < 0)]
a[np.logical_or(a>5,a<0)]

array([-6.71149229, -2.17809525,  8.57545287, -5.31680944, -5.84956773,
       -8.57309185, -5.76927816, -9.8563885 , -1.8064904 , -6.96541888,
       -2.77797572, -6.22511018, -7.55583726])

# 聚合函数

In [47]:
# 1. sum
np.sum(a,axis=0)

array([-22.25000302, -10.72534913,  -7.50604581, -10.08126237,
        -7.41240435])

In [48]:
# 计算元素的积
np.prod(a,axis=0)

array([-400.77794201,  -34.90814664,  526.16495724,  112.13813404,
          2.5747352 ])

In [51]:
np.mean(a,axis=0)

array([-7.41666767, -3.57511638, -2.50201527, -3.36042079, -2.47080145])

In [53]:
np.std(a,axis=0)

array([0.82426021, 1.5707161 , 7.97200397, 4.44498527, 2.53151061])

In [57]:
print(a)
print(np.min(a,axis=0))
print(np.argmin(a,axis=0))

[[-6.71149229 -2.17809525  8.57545287 -5.31680944 -5.84956773]
 [-8.57309185 -5.76927816 -9.8563885   2.79138433 -1.8064904 ]
 [-6.96541888 -2.77797572 -6.22511018 -7.55583726  0.24365377]]
[-8.57309185 -5.76927816 -9.8563885  -7.55583726 -5.84956773]
[1 1 1 2 0]


In [58]:
np.median(a)

-5.76927815516961

In [59]:
%time sum(np.arange(1000000))

Wall time: 160 ms


D:\ProgramApp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in long_scalars
  """Entry point for launching an IPython kernel.


1783293664

In [60]:
%time np.sum(np.arange(1000000))

Wall time: 3.99 ms


1783293664

# 布尔判断函数：

In [73]:
# 验证任何一个元素是否为真
b = np.arange(0,10)
b.any()

True

In [77]:
(a>=0).any()

True

In [81]:
 #按照列进行排序，因为指定了axis=0
np.sort(a,axis=0)

array([[-6.71149229, -2.17809525,  8.57545287, -5.31680944, -5.84956773],
       [-8.57309185, -5.76927816, -9.8563885 ,  2.79138433, -1.8064904 ],
       [-6.96541888, -2.77797572, -6.22511018, -7.55583726,  0.24365377]])

In [82]:
b = np.random.randint(0,10,size=(3,5))
b

array([[2, 8, 4, 3, 7],
       [3, 4, 4, 2, 9],
       [9, 9, 5, 5, 2]])

In [83]:
b.sort()

In [84]:
b

array([[2, 3, 4, 7, 8],
       [2, 3, 4, 4, 9],
       [2, 5, 5, 9, 9]])

In [88]:
# 返回排序后的下标值
np.argsort(a,axis=0)

array([[1, 1, 1, 2, 0],
       [2, 2, 2, 0, 1],
       [0, 0, 0, 1, 2]], dtype=int64)

In [90]:
# np.sort 默认会采用升序排序。如果我们想采用降序排序， 可以使用负号
-np.sort(-a)

array([[ 8.57545287, -2.17809525, -5.31680944, -5.84956773, -6.71149229],
       [ 2.79138433, -1.8064904 , -5.76927816, -8.57309185, -9.8563885 ],
       [ 0.24365377, -2.77797572, -6.22511018, -6.96541888, -7.55583726]])

In [91]:
#  #排序后的结果就是降序的
indexes = np.argsort(-a)
#  #从a中根据下标提取相应的元素
np.take(a,indexes)

array([[ 8.57545287, -2.17809525, -5.31680944, -5.84956773, -6.71149229],
       [-5.31680944, -5.84956773, -2.17809525, -6.71149229,  8.57545287],
       [-5.84956773, -2.17809525,  8.57545287, -6.71149229, -5.31680944]])

# 其他函数补充：

In [92]:
# 1. apply_along_axis：
c = np.random.randint(0,100,size=(3,20))
c

array([[31,  1, 69,  3, 92, 95, 47, 61, 51, 15, 41, 63, 27, 88, 30, 49,
        90, 93, 21, 89],
       [82, 39, 25, 20, 15, 88, 83, 91, 83, 61, 10,  0, 33, 11, 36, 95,
        50, 54, 41, 27],
       [11, 71, 17, 66, 83, 30, 26, 10, 26, 58, 29, 28, 86, 57, 29, 49,
        57, 31, 74, 35]])

##### np.apply_along_axis ：沿着某个轴执行指定的函数

In [99]:
# def get_mean(x):
#     y = x[np.logical_and(x!=x.max(),x!=x.min())].mean()
#     return y

# # 求数组a按行求均值，并且要去掉最大值和最小值。
np.apply_along_axis(lambda x:x[np.logical_and(x!=x.max(),x!=x.min())].mean(),axis=0,arr=c)

D:\ProgramApp\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: Mean of empty slice.
  after removing the cwd from sys.path.
D:\ProgramApp\Anaconda3\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


array([31., 39., 25., 20., 83., 88., 47., 61., 51., 58., 29., 28., 33.,
       57., 30., nan, 57., 54., 41., 35.])

In [102]:
# np.linspace ：用来将指定区间内的值平均分成多少份
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [103]:
d = np.random.randint(0,10,size=(3,5))
d

array([[8, 0, 1, 0, 7],
       [4, 9, 7, 3, 3],
       [4, 0, 9, 4, 0]])

In [108]:
np.unique(d,return_counts=True)

(array([0, 1, 3, 4, 7, 8, 9]), array([4, 1, 2, 3, 2, 1, 2], dtype=int64))